name: Deploy Laravel CRM

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.topscripts.in
          username: dev@avengers.topscripts.in
          password: Baseline@123
          protocol: ftps
          port: 21
          server-dir: /harsh/laravel-CRM/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            .env
